### ISSUE TITLE
请问一下大神，fastdfs怎么弄呢？

### ISSUE THREAD

**Issue by Xw3C** [JustCoding-Hai/subtlechat#1]

**Comment by Xw3C** [comment]
项目跑不起来。。😭

**Comment by JustCoding-Hai** [comment]
https://github.com/JustCoding-Hai/subtlechat/wiki/5.%E9%98%BF%E9%87%8C%E4%BA%91%E4%B8%8A%E6%90%AD%E5%BB%BAFastDFS%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8   可以看看我这里给的教程哦，需要阿里云服务器

**Comment by JustCoding-Hai** [comment]
用阿里云OSS会方便些，不需要安装直接可以用，将上传文件的代码改成OSS的就可以了

**Comment by Xw3C** [comment]
谢谢啦，我研究一下，不懂在请教一下您！😀

**Comment by JustCoding-Hai** [comment]
不客气~
